### PR TITLE
Get gov file

### PR DESCRIPTION
**Pull request by vibhagogu**

### CODE REVIEW

**Comment by vibhagogu** [comment]
This merges all our work with the Get_gov_file function into main

**Comment by abeltranandrade** [comment]
We peer-programmed the end and it worked on all our computers so it is good to merge to the main

**Comment by lmikhelashvili** [comment]
Looks good to merge!

**Comment by abeltranandrade** [comment]
We decided not to close/delete the branch, in case we want to do more tweaks to this function in our next sprint

**Pull request merged**
